/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MascotaLila() {
    const { nodes, materials } = useGLTF("./Modelos/Mascotas/mascotaLila.glb");
    return (
        <>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Vert005.geometry}
                material={materials.piel}
                position={[-0.53, 0.89, -0.09]}
                rotation={[-0.01, 0.01, -0.43]}
                scale={0.5}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Vert001.geometry}
                material={materials.piel}
                position={[0.6, 0.86, -0.11]}
                rotation={[3.13, 0.01, -0.43]}
                scale={-0.5}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pipas005.geometry}
                material={materials.maceta}
                position={[0.72, 3.04, 0.68]}
                rotation={[-0.25, 0, 0]}
                scale={0.07}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pipas004.geometry}
                material={materials.maceta}
                position={[0.81, 2.82, 0.74]}
                rotation={[-0.31, 0, 0]}
                scale={0.07}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pipas003.geometry}
                material={materials.maceta}
                position={[0.65, 2.83, 0.84]}
                rotation={[-0.2, 0, 0]}
                scale={0.07}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pipas002.geometry}
                material={materials.maceta}
                position={[-0.72, 3.02, 0.68]}
                rotation={[2.79, 0, 0]}
                scale={-0.07}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pipas001.geometry}
                material={materials.maceta}
                position={[-0.81, 2.81, 0.74]}
                rotation={[2.78, 0, 0]}
                scale={-0.07}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pipas.geometry}
                material={materials.maceta}
                position={[-0.65, 2.81, 0.84]}
                rotation={[2.84, 0, 0]}
                scale={-0.07}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.oreja_2.geometry}
                material={materials.ropa}
                position={[-0.8, 3.79, 0.01]}
                rotation={[-1.52, -0.56, -0.39]}
                scale={-0.3}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.oreja_.geometry}
                material={materials.ropa}
                position={[0.74, 3.81, 0.01]}
                rotation={[1.62, -0.56, -0.39]}
                scale={0.3}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ojo002.geometry}
                material={materials.nariz}
                position={[0.4, 2.92, 0.88]}
                rotation={[-3.08, -0.45, 0.13]}
                scale={-0.16}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ojo_maceta001.geometry}
                material={materials.nariz}
                position={[-0.51, 0.42, 0.57]}
                rotation={[-2.72, 0.45, 2.07]}
                scale={0.06}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ojo_maceta.geometry}
                material={materials.nariz}
                position={[0.48, 0.42, 0.57]}
                rotation={[0.42, 0.45, 2.07]}
                scale={-0.06}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ojo.geometry}
                material={materials.nariz}
                position={[-0.43, 2.91, 0.86]}
                rotation={[0.06, -0.45, 0.13]}
                scale={0.16}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.nariz.geometry}
                material={materials.ropa}
                position={[0, 2.83, 1.09]}
                rotation={[-0.15, 0, 0]}
                scale={0.07}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mofletes001.geometry}
                material={materials["Material mofletes"]}
                position={[-0.27, 2.62, 1.05]}
                rotation={[-3.03, 0.39, 3.06]}
                scale={-0.15}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mofletes.geometry}
                material={materials["Material mofletes"]}
                position={[0.34, 2.62, 1.02]}
                rotation={[0.15, 0.39, 3.02]}
                scale={0.15}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.maceta.geometry}
                material={materials.maceta}
                scale={1.05}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.cuerpo.geometry}
                material={materials.ropa}
                position={[0.03, 1.43, 0]}
                scale={0.48}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube013.geometry}
                material={nodes.Cube013.material}
                position={[-0.56, 3.84, 0.12]}
                rotation={[-1.05, -0.48, -1.57]}
                scale={0.12}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube012.geometry}
                material={nodes.Cube012.material}
                position={[-0.42, 3.89, 0.21]}
                rotation={[-1.05, -0.48, -1.57]}
                scale={0.12}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube009.geometry}
                material={nodes.Cube009.material}
                position={[-0.41, 3.81, 0.36]}
                rotation={[-1.05, -0.48, -1.57]}
                scale={0.12}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube008.geometry}
                material={nodes.Cube008.material}
                position={[-0.53, 3.73, 0.38]}
                rotation={[-1.05, -0.48, -1.57]}
                scale={0.12}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube007.geometry}
                material={nodes.Cube007.material}
                position={[-0.64, 3.73, 0.25]}
                rotation={[-1.05, -0.48, -1.57]}
                scale={0.12}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube006.geometry}
                material={materials["Material.001"]}
                position={[-0.53, 3.84, 0.24]}
                rotation={[-1.05, -0.48, -1.57]}
                scale={0.07}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube005.geometry}
                material={materials["Material.003"]}
                position={[0.46, 2.92, 0.97]}
                scale={0.03}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004.geometry}
                material={materials["Material.003"]}
                position={[-0.49, 2.91, 0.92]}
                scale={0.03}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube003.geometry}
                material={materials["Material.003"]}
                position={[0.39, 2.95, 0.95]}
                rotation={[-Math.PI, 0, 0]}
                scale={-0.06}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002.geometry}
                material={materials["Material.003"]}
                position={[-0.42, 2.95, 0.92]}
                scale={0.06}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001.geometry}
                material={materials.ropa}
                position={[0.58, 1.78, 0]}
                scale={0.19}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={materials.ropa}
                position={[-0.53, 1.77, 0.01]}
                scale={0.19}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ceja002.geometry}
                material={materials.cejas}
                position={[-0.3, 3.1, 0.83]}
                rotation={[2.4, -0.39, 0.28]}
                scale={-0.06}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ceja.geometry}
                material={materials.cejas}
                position={[0.28, 3.1, 0.83]}
                rotation={[-0.74, -0.39, 0.28]}
                scale={0.06}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.cara.geometry}
                material={materials.piel}
                position={[-2.21, 2.83, -0.65]}
                scale={0.96}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.cabeza_003.geometry}
                material={materials.ropa}
                position={[0.01, 2.95, -0.01]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.boca.geometry}
                material={materials.cejas}
                position={[0.07, 2.59, 0.96]}
                scale={0.11}
            />
        </>
    );
}

useGLTF.preload("./Modelos/Mascotas/mascotaLila.glb");
