/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useBox } from '@react-three/cannon';

export function Mesa() {
    const { nodes, materials } = useGLTF("./Modelos/Mesa.glb");

    const [mesita] = useBox(() => ({
        mass: 1,
        type: "Static",
        position: [3.45, 0.65, -4],
        args: [2, 1.5, 1.3]
    }));


    return (
        <group ref={mesita} dispose={null} scale={1.2}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Node-Mesh"].geometry}
                material={materials.mat20}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes["Node-Mesh_1"].geometry}
                material={materials.mat15}
            />
        </group>
    );
}

useGLTF.preload("./Modelos/Mesa.glb");
