/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Tocadiscos({color, controlMusica, PlayerApi, controlNextSong}) {
    const { nodes, materials } = useGLTF("./Modelos/Tocadiscos.glb");
    const colorMaterial = new THREE.MeshBasicMaterial({ color: color });
    const posicionTocadiscos = [3, 0.81, -3.95];


    const playerPosition = useRef([0, 0, 0]);


    //Se ejecuta al hacer click al tocadiscos
    const handleChangeSong = () => {

        const umbral = 4;

        //Obtenemos la posicion del jugador
        PlayerApi.position.subscribe((pos) => {
            playerPosition.current = pos;
        });

        //Calculamos la distancia entre el jugador y el tocadiscos
        const distancia = Math.sqrt(
            Math.pow(playerPosition.current[0] - posicionTocadiscos[0], 2) +
            Math.pow(playerPosition.current[1] - posicionTocadiscos[1], 2) +
            Math.pow(playerPosition.current[2] - posicionTocadiscos[2], 2)
        );

        //Si la distancia es menor que el umbral, se ejecuta la funcion de pasar a la siguiente cancion
        if (distancia < umbral) {
            if (controlMusica=== true) {
                controlNextSong(true)
            }
        }

    };

    return (
        <group dispose={null} position={posicionTocadiscos} scale={0.008} onClick={handleChangeSong}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferCyl001.geometry}
                material={materials["07___Default"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferBox003.geometry}
                material={colorMaterial}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferBox004.geometry}
                material={colorMaterial}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferBox010.geometry}
                material={materials["04___Default"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferCyl008.geometry}
                material={materials["04___Default"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferCyl009_1.geometry}
                material={materials["04___Default"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferCyl009_1_1.geometry}
                material={materials["05___Default"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferCyl009_1_2.geometry}
                material={materials["06___Default"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferCyl009_1_3.geometry}
                material={materials["09___Default"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferCyl009_1_4.geometry}
                material={colorMaterial}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferCyl009_1_5.geometry}
                material={materials["02___Default"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferCyl009_1_6.geometry}
                material={materials["07___Default"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferBox013.geometry}
                material={materials["07___Default"]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ChamferBox014.geometry}
                material={materials["07___Default"]}
            />
        </group>
    );
}

useGLTF.preload("./Modelos/Tocadiscos.glb");