/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Arbol1Azul(props) {
    const { nodes, materials } = useGLTF("./Modelos/Entorno/arbol1Azul.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder010.geometry}
                material={materials["arbol tronvo.002"]}
                position={[0, 1.13, -0.23]}
                scale={0.72}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder009.geometry}
                material={materials["arbol copa .002"]}
                position={[0, -0.04, 0]}
                scale={0.16}
            />
        </group>
    );
}

useGLTF.preload("./Modelos/Entorno/arbol1Azul.glb");