/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Arbol2Lila(props) {
    const { nodes, materials } = useGLTF("./Modelos/Entorno/arbol2Lila.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder013.geometry}
                material={materials["arbol tronvo.003"]}
                position={[0, 0.13, 0]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube015.geometry}
                material={materials["arbol copa .003"]}
                position={[0, 1.32, 0]}
                scale={0.65}
            />
        </group>
    );
}

useGLTF.preload("./Modelos/Entorno/arbol2Lila.glb");
