/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Arbol1Lila(props) {
    const { nodes, materials } = useGLTF("./Modelos/Entorno/arbol1Lila.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder012.geometry}
                material={materials["arbol copa .003"]}
                position={[0, -0.03, 0]}
                scale={0.16}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder011.geometry}
                material={materials["arbol tronvo.003"]}
                position={[0, 1.13, -0.23]}
                scale={0.72}
            />
        </group>
    );
}

useGLTF.preload("./Modelos/Entorno/arbol1Lila.glb");
