/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Arbol2Azul(props) {
    const { nodes, materials } = useGLTF("./Modelos/Entorno/arbol2Azul.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder008.geometry}
                material={materials["arbol tronvo.002"]}
                position={[0, 0.12, 0]}
                scale={0.1}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube014.geometry}
                material={materials["arbol copa .002"]}
                position={[0, 1.32, 0]}
                scale={0.65}
            />
        </group>
    );
}

useGLTF.preload("./Modelos/Entorno/arbol2Azul.glb");
