/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Arbol1Verde(props) {
    const { nodes, materials } = useGLTF("./Modelos/Entorno/arbol1Verde.glb");
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder019.geometry}
                material={materials["arbol tronvo.001"]}
                position={[0, 1.13, 0.23]}
                rotation={[0, 0, -Math.PI]}
                scale={-0.72}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder018.geometry}
                material={materials["arbol copa .001"]}
                position={[0, -0.01, 0]}
                rotation={[0, 0, -Math.PI]}
                scale={-0.16}
            />
        </group>
    );
}

useGLTF.preload("./Modelos/Entorno/arbol1Verde.glb");
